services:

  client:
    build: .
    networks:
      - habitica
    environment:
      - BASE_URL=http://server:3000
    ports:
        - "8080:8080"
    command: ["npm", "run", "client:dev"]
    depends_on:
      - server

  server:
    build: .
    ports:
      - "3000:3000"
    networks:
      - habitica
    environment:
      - NODE_DB_URI=mongodb://mongo/habitrpg
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.17
    container_name: mongodb_replica
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    healthcheck:
      test: mongosh --eval "rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]})"
      interval: 1s
      timeout: 30s
      retries: 3
    volumes:
      - "mongodata:/data/db"

networks:
  habitica:
    driver: bridge

volumes:
    mongodata:
